name: CI

on:
  push:
    branches: ["main", "work"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ matrix.python-version }}
      - name: Install Poetry
        run: pip install poetry
      - name: Install deps
        run: |
          poetry install --no-interaction
      - name: Run tests
        run: |
          poetry run pytest -q
